services:
  app:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: testingdb.c5cw0e2mcgzs.us-east-1.rds.amazonaws.com
      MYSQL_USER: admin
      MYSQL_PASSWORD: Admin#123
      MYSQL_DB: todo_app_db
